version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8001
    networks:
      - proyecto_net
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - proyecto_net
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - proyecto_net

networks:
  proyecto_net:

volumes:
  mongo_data: