version: "3.9"

services:
  frontend:
    build: ./frontend
    restart: always
    expose:
      - 5173
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8001
    networks:
      - proyecto_net
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    restart: always
    expose:
      - 8001
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - proyecto_net
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    expose:
      - 2717
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo_init/:/docker-entrypoint-initdb.d
    networks:
      - proyecto_net

networks:
  proyecto_net:

volumes:
  mongo_data: